- name: Generate inventory from labs.yaml
  hosts: localhost
  gather_facts: false
  vars_files:
    - ./labs.yaml
  tasks:
    - name: Generate dynamic inventory
      ansible.builtin.template:
        src: ./inventory-template.yaml.j2
        dest: ./inventory.yaml
        mode: "0755"
