- name: Deploy single-node jalapeno-bmp-demo
  hosts: all
  vars:
    lab_user: ins
    kubectl_version: 1.34.1
    helm_version: 3.19.0
    microk8s_channel: 1.34/stable
    containerlab_version: 0.71.1
    containerlab_xrd: true
    go_version: 1.25.4
  tasks:
    - name: Deploy Kubernetes, Containerlab, and dependencies (as root)
      become: true
      block:
        # Kubernetes and CLI tools
        - name: Deploy MicroK8s
          ansible.builtin.include_tasks: ./tasks/microk8s.yaml
        - name: Add kubectl for easier management
          ansible.builtin.include_tasks: ./tasks/kubectl.yaml
        - name: Add Helm for jalapeno installation
          ansible.builtin.include_tasks: ./tasks/helm.yaml

        # Containerlab and dependencies
        - name: Deploy Docker
          ansible.builtin.include_tasks: ./tasks/docker.yaml
        - name: Deploy Containerlab
          ansible.builtin.include_tasks: ./tasks/containerlab.yaml
        - name: Install Go
          ansible.builtin.include_tasks: ./tasks/go.yaml

    - name: Deploy Jalapeno, JAGW, and Networking Lab (as user)
      block:
        # Deploy Jalapeno stack
        - name: Install Jalapeno via Helm
          ansible.builtin.include_tasks: ./tasks/jalapeno.yaml
        - name: Install JAGW via Helm
          ansible.builtin.include_tasks: ./tasks/jagw.yaml

        # Deploy Containerlab topology
        - name: Deploy Containerlab topology
          vars:
            clab_file: ../clab/bmp.clab.yaml
          block:
            - name: Deploy lab via containerlab
              ansible.builtin.command: containerlab deploy --topo {{ clab_file }}
              args:
                chdir: "/home/{{ lab_user }}"
              register: clab_result

            - name: Show containerlab deploy output
              ansible.builtin.debug:
                var: clab_result.stdout_lines
