- name: Add Docker repository and keys
  ansible.builtin.deb822_repository:
    name: docker
    types: deb
    uris: "https://download.docker.com/linux/{{ ansible_facts.distribution | lower }}"
    suites: "{{ ansible_facts.distribution_release }}"
    components: stable
    architectures: amd64
    signed_by: "https://download.docker.com/linux/{{ ansible_facts.distribution | lower }}/gpg"

- name: Install Docker
  ansible.builtin.apt:
    name:
      - docker-ce
      - docker-ce-cli
      - containerd.io
      - docker-buildx-plugin
      - docker-compose-plugin
    state: present
    update_cache: true
    cache_valid_time: 3600

- name: Add user to docker group
  ansible.builtin.user:
    name: "{{ lab_user }}"
    groups: docker
    append: true

- name: Reset SSH connection to allow user changes
  ansible.builtin.meta: reset_connection

- name: Start Docker service
  ansible.builtin.service:
    name: docker
    enabled: true
    state: started
