- name: Extract Go
  ansible.builtin.unarchive:
    remote_src: true
    src: "https://go.dev/dl/go{{ go_version }}.linux-amd64.tar.gz"
    dest: /usr/local
    owner: root
    group: root
    mode: "0755"

- name: Add to Go PATH
  ansible.builtin.lineinfile:
    path: /etc/profile
    line: 'export PATH=$PATH:/usr/local/go/bin'
    insertafter: EOF

- name: Install Go Language Server (gopls)
  ansible.builtin.apt:
    name:
      - gopls
    state: present
